language: python
python:
  - "3.6.4"
install:
  - pip3 install -r requirements.txt
before_script:
  - export DATABASE_URL='postgres://xdsguwvnzbwshq:13891e960ab717a1ba2e12243f600df216f33a75d0afbafa9726f35120a7d7db@ec2-184-72-219-186.compute-1.amazonaws.com:5432/dbbq83uiva9744'
  - export UPLOAD_PATH='static/audio'
  - export SECRET_KEY="b'\x8a\xd1D~\x11\xaf\xa8\xa4\xfe\t\xf0j\x82\xb0\xdaS5\xa1\x18\xec\xdeS\x8b5'"
  - export FLASK_APP='thetextinbox/app.py'

script:
  - python3 thetextinbox/tests.py
