language: python
python:
  - "3.6.4"
install:
  - pip3 install -r requirements.txt
before_script:
  - export SECRET_KEY="b'\x8a\xd1D~\x11\xaf\xa8\xa4\xfe\t\xf0j\x82\xb0\xdaS5\xa1\x18\xec\xdeS\x8b5'"
  - export FLASK_APP='app.py'

script:
  - python3 tests.py
